/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prps;

/**
 *
 * @author User
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    int type;
    int Id;
    javax.swing.JFrame prev;
    public Report(int type, int id, javax.swing.JFrame prev) 
    {
        this.Id = id;
        this.prev = prev;
        this.type = type;
        initComponents();
        getReport();
    }
    
    private void getReport()
    {
        if (type == 1) 
        {
            jLabel1.setText("Количество отработанных часов в неделю");
            int hours = DBConn.getHours(Id);
            jTextField1.setText(Integer.toString(hours));
        }
        if (type == 2) 
        {
            jLabel1.setText("Количество заказов");
            int orders = DBConn.getOrders(Id);
            jTextField1.setText(Integer.toString(orders));
        }
        if (type == 3) 
        {
            jLabel1.setText("Количество отпускных");
            int voc = DBConn.getVocPayments(Id);
            jTextField1.setText(Integer.toString(voc));
        }
        if (type == 4) 
        {
            jLabel1.setText("Количество сверхурочных часов");
            int hours = DBConn.getOverHours(Id);
            jTextField1.setText(Integer.toString(hours));
        }
        if (type == 5) 
        {
            jLabel1.setText("Количество отпускных часов");
            int vocDays = DBConn.getOrders(Id);
            jTextField1.setText(Integer.toString(vocDays));
        }
        if (type == 6) 
        {
            jLabel1.setText("Зарплата");
            int s = DBConn.getSalary(Id);
            jTextField1.setText(Integer.toString(s));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setTitle("Отчёт");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Отчёт :");

        jTextField1.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
